### ISSUE TITLE
windows 10  python 3.6,运行错误。

### ISSUE THREAD

**Issue by bs111** [meituan/lyrebird-android#3]
pip3 isntall lyrebird
pip3 install lyrebird-ios
pip3 install lyrebird-android
pip3 install lyrebird-api-coverage
lyrebird --help
以上都是正确的。

lyrebird v start 该命令报错。如下：
C:\Users\borla>lyrebird v start
Traceback (most recent call last):
  File "d:\python36\lib\site-packages\lyrebird\mock\logger_helper.py", line 45, in init_logger_settings
    disable_existing_loggers=False)
  File "d:\python36\lib\logging\config.py", line 84, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "d:\python36\lib\logging\config.py", line 147, in _install_handlers
    args = eval(args, vars(logging))
  File "<string>", line 1
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python36\Scripts\lyrebird.exe\__main__.py", line 9, in <module>
  File "d:\python36\lib\site-packages\lyrebird\manager.py", line 226, in run
    fire.Fire(CommandLine)
  File "d:\python36\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "d:\python36\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "d:\python36\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "d:\python36\lib\site-packages\lyrebird\manager.py", line 199, in start
    self.server.start()
  File "d:\python36\lib\site-packages\lyrebird\manager.py", line 114, in start
    init_logger_settings(verbose=self.verbose)
  File "d:\python36\lib\site-packages\lyrebird\mock\logger_helper.py", line 53, in init_logger_settings
    disable_existing_loggers=False)
  File "d:\python36\lib\logging\config.py", line 84, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "d:\python36\lib\logging\config.py", line 147, in _install_handlers
    args = eval(args, vars(logging))
  File "<string>", line 1
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

C:\Users\borla>

**Comment by yumiguan** [comment]
Windows环境尚没有适配。已标记为缺陷。
